theme: jekyll-theme-minimal
title: ZhangJing Mok's Homepage
description: Welcome to my personal webpage! Stay updated with my latest projects and academic pursuits.

url: "https://nokia2255.github.io"
