theme: jekyll-theme-minimal
title: Mok Zhang Jing's Homepage
description: Bookmark to stay updated on my latest projects and endeavors!

# Optional: Add a URL if you're using a custom domain
url: "https://nokia2255.github.io"
